### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by 1itt1eB0y** [logto-io/logto#1575]
Docker Prerelease
When using http, it says `Crypto.subtle is unavailable in insecure contexts (non-HTTPS).`
When using https, it says `{"message":"无效返回链接, 该 redirect_uri 未被此应用注册。","code":"oidc.invalid_redirect_uri","data":{"error_description":"redirect_uri did not match any of the client's registered redirect_uris"}}`
The dashboard can't be reached.

And there isn't a command which called `docker compose`.
Please write a really useful document to build it with self-hosted.

**Comment by gao-sun** [comment]
You need to use `localhost` to load admin console under HTTP, or specify env `ENDPOINT` when using a custom domain.

We'll update docs, but I'll close this issue since it doesn't follow our template and provides a vague context which is not useful. You can re-open it once the content is organized.

@demonzoo @simeng-li would you like to add a linear issue for updating the docs? thanks.

**Comment by demonzoo** [comment]
[Linear issue](https://linear.app/silverhand/issue/LOG-3735/update-docs-to-mention-https-and-endpoint-in-self-hosted-scenario) created to update the documentation.
