### ISSUE TITLE
feature request: flutter sdk

### ISSUE THREAD

**Issue by naliazheli** [logto-io/logto#1649]
### What problem did you meet?

I want to use flutter to build my app,but found no sdk.
### Describe what you'd like Logto to have

support flutter...

**Comment by gao-sun** [comment]
We do have a plan on Flutter SDK. Please follow the template if you want to keep the issue open.

**Comment by gao-sun** [comment]
We do have a plan. You can check out our public roadmap.

**Comment by flobaader** [comment]
@gao-sun is there any plan when to release the flutter SDK? because q3 ends in a few weeks :)
It would a massive game changer for us if you would support flutter!

**Comment by gao-sun** [comment]
@simeng-li who's actively developing Flutter SDK. would you like to briefly update? thanks.

**Comment by simeng-li** [comment]
Hey, @flobaader glad to have you with us. I have been actively working on this for about 1-2 weeks. To be honest, I have zero experience in Flutter development before and also get a couple of other tasks running simultaneously, the process is much slower than I expected.  Hope you understand.  

Since you asked, it would be a great pleasure for us if we can work this out. I'll shift some of my efforts and see how far I can go. I might miss the Q3 goal, but hopefully not much, a couple of days maybe?  I do have the major API and logic implemented, but spend some time hanging around at the client interaction parts like webview interactions, and storage.

Meanwhile, it would be a huge help if you would like to co-op on the flutter SDK.  Also would love to have some context of your project, what platforms do you have the flutter project running on?

**Comment by flobaader** [comment]
Hey @simeng-li , we are using Flutter on iOS and Android. We have a few flutter developers in our company so if you need any help on a specific topic we could arrange that :)

**Comment by simeng-li** [comment]
Bravo! Hands-on it, will keep you posted.

**Comment by JulianHartl** [comment]
Hey @simeng-li, I'd be happy to help you out with the Flutter SDK. Just let me know when you need any help or support :)
