### ISSUE TITLE
question: Why is the administrator hidden by default?

### ISSUE THREAD

**Issue by myesn** [logto-io/logto#1944]
### What problem did you meet?

The hideAdminUser parameter is hardcoded to true:

[https://github.com/logto-io/logto/blob/5fe0cf4257a72f96fc439132c7b5b58e07352aa3/packages/console/src/pages/Users/index.tsx#L39](https://github.com/logto-io/logto/blob/5fe0cf4257a72f96fc439132c7b5b58e07352aa3/packages/console/src/pages/Users/index.tsx#L39)

### Describe what you'd like Logto to have

So I can't change the password of admin or bind the mailbox etc. Why is it like this?

**Comment by charIeszhao** [comment]
Hi myesn, good question. It is because we wanted to treat admin user differently, as in v1 we only have 1 admin, and it doesn't make too much sense to mix admin (yourself) with users of your product.

As of now, you can reset your admin password in the "Settings" page.
<img width="930" alt="image" src="https://user-images.githubusercontent.com/12833674/190540648-d6b062bb-fbfe-46b0-911b-60350f6ec235.png">

Unfortunately, binding the email with admin account is currently not supported. However, we are actively designing a feature called "Profile ful-fulling" right now, and you will be able to see a new "Profile" page in the next few weeks. Please stay tuned!

**Comment by charIeszhao** [comment]
You can join our [discord server](https://discord.gg/N8qyhmxz) if you haven't done so, and you'll be able to get instant release notifications and dev team support.
