### ISSUE TITLE
bug: Name displays as messy code in Ant Design Pro when using Chinese

### ISSUE THREAD

**Issue by Hengyu-DU** [logto-io/logto#1945]
### Describe the bug
**Name** displays as messy code in Ant Design Pro when using Chinese.
#1916 

### Expected behavior
Chinese "Name" can be displayed as how it be set before. 

### How to reproduce?

1. create an account
2. change the "name" of the account in Chinese in Logto Console
3. the account data accessed in web contains messy code 

### Context

OS: 

Environment: Windows 10 ; Mac

Logto version:  logto:prerelease

Node version: v16.17.0

Postgres version:  12

Command of starting Logto: docker run

### Screenshots
![image](https://user-images.githubusercontent.com/88032313/190563790-060a9bf8-5a2f-418a-851b-8a72fa721186.png)

**Comment by charIeszhao** [comment]
Hi @Hengyu-DU , thanks for reporting! And yes, this is a legit problem... We just never found it for we never tried decoding CJK user name from `idToken`.

After debugging, we have located the root cause in one of our utility methods, which is used to convert back and forth between raw string and base64 string.

We'll provide a fix ASAP, and ship it in the next prerelease beta version (most likely next Monday or Tuesday). Please stay tuned and I will also keep you updated in this ticket.

**Comment by charIeszhao** [comment]
@Hengyu-DU This issue has been fixed in latest JS SDKs as well as Logto master branch. Cheers!

Please upgrade your `@logto/react` SDK to latest (v1.0.0-beta.6) in order to get rid of this annoying bug. Let me know if you have further questions.

Thank you for using Logto.
Charles

**Comment by Hengyu-DU** [comment]
Problem is resolved.
Thank you, Charles
