### ISSUE TITLE
feature request: support node 16 or decoupling dependency

### ISSUE THREAD

**Issue by songhn233** [logto-io/logto#3149]
### What problem did you meet?
The current node 16 and 18 are both LTS versions, but cli or other packages are restricted to node 18 and above, which is perhaps a bit radical.
Because it's true that on a PC it's easier to switch versions via nvm and so on, but after all this is a self-hosting application, on a server sometimes it's not easy to use node 18 (like centos 7 or some cloud environments with limited runtime), so maybe there should be some more general solutions for installation.

For docker deploy, could `npx @logto/cli db seed` provide a bash script or some other solution to avoid forced dependency on node 18?

### Describe what you'd like Logto to have
support node 16 for cli or other packages

**Comment by songhn233** [comment]
By the way, you can actually modify `docker-compose.yml` to adapt to your current environment, for example by directly modifying the PostgreSQL declaration to your current database in compose. 

I think the documentation could be more descriptive, the description of the current version gives the impression that this is just a quick test and that two other options should be used to deploy.

**Comment by charIeszhao** [comment]
No, node 16 is no longer in LTS and the its end of life date is [Sep 11, 2023](https://nodejs.org/en/blog/announcements/nodejs16-eol/). Therefore, it doesn't worth all the effort trying to make Logto compatible with node 16. Not to mention, our underlying dependency `node-oidc-provider` has also dropped support for node 16, which makes it even harder to support node 16.

As for the docker compose file, we made that warning delibrately in order to prevent potential severe data losses from our users, as some of them might not be experienced with docker. If you are a more experienced user and know what you are doing, you can always modify the config file yourself to meet your needs, which is also the spirit of open source.

I'm closing the ticket as "Not Planned". Thank you for reaching out and please feel free to contact us again if you have anything.
