### ISSUE TITLE
bug: /oidc/token fails with CORS error in case of Machine to Machine application

### ISSUE THREAD

**Issue by jay-dee7** [logto-io/logto#3348]
### Describe the bug
When I setup a Machine-to-Machine application, and I try to get an access token using `POST /oidc/token`, it fails with the following error:

```json
{
  "error": "invalid_request",
  "error_description": "origin http://localhost:3000 not allowed for client: eS1Ds3pVGnocjTN9XYQVR"
}
```

### Expected behavior
There should be a way to set CORS Allowed Origin, from the Admin Console. We have the option for setting this on other app kinds.

I went on to insert `custom_client_metadata='{"corsAllowedOrigins": ["http://localhost:3000"]}'` into the applications table via PostgreSQL CLI and it started working fine.

### How to reproduce?
Follow the instructions here - https://docs.logto.io/docs/recipes/integrate-logto/machine-to-machine/ and use normal REST APIs (curl/Postman/fetch) to fetch an access_token from the `/oidc/token` endpoint. The API fails with the error mentioned above.
### Context

OS: `MacOS Ventura`

Environment: `Local (using pnpm)`

Logto version: `v1.0.0-rc.3`

Node version: `v18.12.0`

Postgres version: `14`

Command of starting Logto: `pnpm run dev`

**Comment by gao-sun** [comment]
@jay-dee7 thanks for the update. @wangsijie would you like to double check if there's anything we can do better in this case?

**Comment by wangsijie** [comment]
From Admin Console, users can set CORS Allowed Origin for other application except Machine To Machine(M2M), because M2M is expected to run on the server, and the CORS is the "browser" mechanism.

As for your case, it is possible that the code is running in browser side since "SvelteKit" is the mixed framework.

Thanks for the update, let me know if you have any questions on that.
