### ISSUE TITLE
feature request: sqlite support

### ISSUE THREAD

**Issue by yangzhaox** [logto-io/logto#3839]
### What problem did you meet?
I have a web app hosted in a small  vps with 2GB memory and I want to use Logto for social login but don't want to run a progresql in that small server.

### Describe what you'd like Logto to have
Support Sqlite as another choice of db for apps with low-medium traffics.

**Comment by gao-sun** [comment]
Thanks for suggesting. For now it's hard for us to support other databases since we are leveraging some Postgres-specific features. Related #1661.

You can also use [Logto Cloud](https://cloud.logto.io/) to avoid hosting issues, though it's a preview version but we won't delete your data. We'll also make a free tier to use in the official launch.
