### ISSUE TITLE
[Replied] bug: Access token is invalid

### ISSUE THREAD

**Issue by gorrilla10101** [logto-io/logto#4399]
### Describe the bug

The access token is empty/invalid. 
I am using react-oidc-context to login with a react app and have successfully tested it with both authentik and keycloak servers. When trying it with logto the access token was invalid. This is the access token that is returned.  `G-HMSESWae8UFLUliq7KsLe5c2mGLyp6E8r3IKCaNis`  I have a valid id token and there's no errors in the flow. 
### Expected behavior

I expect to have a valid access token at the end of an authorization code + pkce flow. 
### How to reproduce?

Create a react app
Add the AuthProvider component from react-oidc-context and configure it to call logto. 
Start the react app, AuthProvider auto logs in by default so you will be redirected to be logged in. 
After logging in check local storage and see that the access token is incomplete. 
I suspect this will happen in other scenarios but this was the specific case. 
### Context

- [x] Logto Cloud
- [x] Self-hosted, Logto version = 
  - [x] Container (Docker image)
  - [ ] Raw Node.js

**Comment by charIeszhao** [comment]
@gorrilla10101 Hi, it seems you are using a 3rd party plugin `react-oidc-context`. And also the token you acquired seems to be an `opaque` token, which is a non-JWT format string.

In Logto, the `openid` scope is a reserved one and will be applied by default to token requests. So if you don't do anything the OIDC server will assume you are requesting the `userinfo` endpoint. In such case, an `opaque` access token will be issued as the audience is `userinfo` endpoint.

We are using the OAuth [resource](https://docs.logto.io/docs/references/resources/) concept and you'll have to provide the resource when issuing an access token in order to have a JWT format access token. Otherwise, the `opaque` token will be returned.

So if you use Logto React SDK, you'll find we have a `resource` param in `signIn` method. You can only issue an JWT token against the specified `resource` in this way. This is helpful if you have multiple API resources and want to control the access to different resources, since you have one JWT access token to each resource.

But in your case, if you only have one resource and don't want to use Logto official SDKs, then I think you can probably specify it as [default API resource](https://docs.logto.io/docs/references/resources/#default-api) in admin console.
<img width="1209" alt="image" src="https://github.com/logto-io/logto/assets/12833674/dd6ddbcc-868c-4713-8512-ff1f4ca229cd">
Then Logto will not apply 'openid' scope and also always apply your default resource as token audience. This way you can always get a JWT access token, but at the cost of never being able to access OIDC `userinfo` endpoint to fetch userinfo from server. You can use management API instead, though. But that'll be another topic.

**Comment by ferryferry** [comment]
I also got back the opaque token. I'm trying to call my protected API via Postman - therefore I want to configure postman to obtain a token for me with "Authorization Code (With PKCE)".

![image](https://github.com/logto-io/logto/assets/17270672/6be3d93e-60be-4e1c-9aa5-a3403d97a679)
Is it possible to get it to work in Postman?

**Comment by ferryferry** [comment]
Hmm, I got it to work by setting the `resource` as well in the token request, and to send it as `Request Body`
<img width="572" alt="image" src="https://github.com/logto-io/logto/assets/17270672/817a7241-0b44-4a0b-adfd-3c963f71fdcb">

However, I'm still not able to refresh my token within Postman.
Refresh token I got back is `b3Hu51cGxHKnJFV9zn27nWcFukGiNLY0ur7N0cnCmBT ` - Is this an `opaque` token as well?

When refreshing the token, the following error is coming back:
<img width="814" alt="image" src="https://github.com/logto-io/logto/assets/17270672/1c8f856e-c1a3-4e76-8099-e508fcacfa86">

**Comment by charIeszhao** [comment]
> Hmm, I got it to work by setting the `resource` as well in the token request, and to send it as `Request Body` <img alt="image" width="572" src="https://user-images.githubusercontent.com/17270672/266798896-817a7241-0b44-4a0b-adfd-3c963f71fdcb.png">
> 
> However, I'm still not able to refresh my token within Postman. Refresh token I got back is `b3Hu51cGxHKnJFV9zn27nWcFukGiNLY0ur7N0cnCmBT ` - Is this an `opaque` token as well?
> 
> When refreshing the token, the following error is coming back in the Postman console: <img alt="image" width="814" src="https://user-images.githubusercontent.com/17270672/266798949-1c8f856e-c1a3-4e76-8099-e508fcacfa86.png">
> 
> ```json
> {
>   "ip": "::ffff:172.18.0.1",
>   "key": "ExchangeTokenBy.RefreshToken",
>   "error": "{\"stack\":\"InvalidRequest: invalid_request\\n    at findClientId (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/token_auth.js:90:19)\\n    at dispatch (/etc/logto/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)\\n    at setWWWAuthenticateHeader (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/token_auth.js:43:17)\\n    at dispatch (/etc/logto/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)\\n    at rejectDupes (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/reject_dupes.js:44:10)\\n    at dispatch (/etc/logto/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)\\n    at assembleParams (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/assemble_params.js:6:10)\\n    at dispatch (/etc/logto/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)\\n    at selectiveBody (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/selective_body.js:49:11)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async noCache (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/no_cache.js:3:3)\\n    at async cors (/etc/logto/node_modules/.pnpm/@koa+cors@4.0.0/node_modules/@koa/cors/index.js:105:16)\\n    at async errorHandler (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/error_handler.js:26:7)\\n    at async ensureSessionSave (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/helpers/initialize_app.js:52:7)\\n    at async contextEnsureOidc (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/context_ensure_oidc.js:4:5)\\n    at async file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/helpers/initialize_app.js:222:5\",\"message\":\"invalid_request\",\"allow_redirect\":true,\"name\":\"InvalidRequest\",\"error\":\"invalid_request\",\"status\":400,\"statusCode\":400,\"expose\":true,\"error_description\":\"client_secret must be provided in the Authorization header\"}",
>   "params": {
>     "resource": "http://dev.api.apteansharedservices.com/",
>     "grant_type": "refresh_token",
>     "refresh_token": "b3Hu51cGxHKnJFV9zn27nWcFukGiNLY0ur7N0cnCmBT"
>   },
>   "result": "Error",
>   "userAgent": "PostmanRuntime/7.32.3",
>   "tokenTypes": []
> }
> ```

Yes, you'll have to add `resource` param when acquiring an access token. And I think we've solve the refresh token issue yesterday on Discord. You'll have to add `clientId` in your request params.

And btw, refresh tokens are opaque tokens, not JWT.

**Comment by charIeszhao** [comment]
Closing the ticket due to inactivity for more than 30 days.
