### ISSUE TITLE
bug: OpenAPI specification invalid for Hasura

### ISSUE THREAD

**Issue by steve-o** [logto-io/logto#4864]
### Describe the bug
Both Hasura and the OAS 3 validator report the bundled `swagger.json` has issues.
```
Invalid spec: Cannot use 'in' operator to search for '$ref' in undefined 
```
### How to reproduce?
Copy & paste the OpenAPI specification into either validator, either "Import from OpenAPI spec" or:

https://apitools.dev/swagger-parser/online/

`docker inspect` shows a version 1.10.1, however the digest does not match those reported by Docker Hub.  As per #3840 the webui should really display the version number somewhere.

### Context
- [x] Self-hosted, Logto version = 1.10.1 (Docker digest `b1a351cdfb51`)
  - [x] Container (Docker image)
  - [ ] Raw Node.js

I'm trying to expose the User API within GraphQL from Hasura.
### Screenshots
<img width="406" alt="hasura-validator" src="https://github.com/logto-io/logto/assets/258627/5b58fabb-1371-4e27-adab-5092cbaf2736">
<img width="578" alt="oas3validator" src="https://github.com/logto-io/logto/assets/258627/58c3724a-0557-4b56-8605-d44c0a91e89b">

**Comment by simeng-li** [comment]
Hi Steve, appreciate the report, we are looking into this.

**Comment by gao-sun** [comment]
@steve-o per `swagger-parser` says, the json itself is valid, and the circular reference issue should be an improvement for the tool. e.g. https://github.com/swagger-api/swagger-ui/issues/5276

since both ReDoc and our [online api references](https://openapi.logto.io/) can render the spec correctly, i doubt if it's a parser bug in Hasura. found similar issue: https://github.com/ardatan/graphql-mesh/issues/1555

would you mind double check with Hasura?

p.s. thank you for letting us know the `swagger-parser` tool, it does help us find some errors that the existing validator didn't catch.

**Comment by gao-sun** [comment]
i've also tried Hasura and was able to repro your issue, unfortunately the error message is too wide to find the exact error location. if we can know it, i'm ok to fix for Hasura.

**Comment by steve-o** [comment]
There is a matching ticket with Hasura, https://github.com/hasura/graphql-engine/issues/9986

FYI: This is no longer a priority for me, but an issue I found whilst testing the two services.  Ideally the Swagger tooling could be more informative.

**Comment by gao-sun** [comment]
@steve-o, thank you for the update! feel free to open issues in the future.
