### ISSUE TITLE
Do I need to recharge to use it ？

### ISSUE THREAD

**Issue by mdxiaohu** [logto-io/logto#4956]

**Comment by xiaoyijun** [comment]
Hi @mdxiaohu , for our Logto Cloud product, we have different subscriptions plans (including free plan) for you to choose from. Please refer to the [pricing page](https://logto.io/pricing) and you can also try all features for free in the [Logto cloud](https://cloud.logto.io) by creating a development tenant.

You may also deploy your own Logto instance since Logto is an opensource project.
