### ISSUE TITLE
Full LogOut with Logto not functioning as expected with next-auth (v4 / v5)

### ISSUE THREAD

**Issue by TorbenHammes** [logto-io/logto#6673]
**Description:**
I am currently using next-auth v5 with Logto as my identity provider (IdP), and I am encountering issues with the logout flow. Specifically, I am able to log out locally, but when I sign in again, I am automatically logged in without being prompted to select an account. I would like to fully log out from both my application and Logto, ensuring that users are prompted to select an account upon re-login.

**Steps to Reproduce:**

	1.	Set up next-auth v5 with Logto as an OAuth provider.
	2.	Implement signOut to log the user out locally.
	3.	Upon re-login using signIn, the user is automatically signed in without being prompted to select an account.

**Expected Behavior:**

- After calling signOut, the user should be logged out from both the local session and the Logto session.
- Upon clicking signIn again, the user should be prompted to choose an account to log in with.

**Actual Behavior:**

- The local logout works correctly, but when signIn is called again, the user is automatically signed back in without the option to choose an account.

**Environment:**

	•	NextAuth.js version: v5 (also tried with v4)
	•	Node.js version: v20.10.0
	•	Next.js version: 14.x
	•	Logto Version: 1.20.0

**Additional context:**

	•	I’ve confirmed that my Logto configuration has the correct post_logout_redirect_uri registered.
	•	The issue appears both locally and in production (Netlify).

Is there any recommended way to fully log out users from both the local session and Logto, ensuring they are prompted to choose an account upon re-login?

Thank you!

**Comment by charIeszhao** [comment]
Thanks for reporting. Here are my two cents:

- Logto does NOT support `select account` prompt right now, so technically you cannot see the account selection page in your app whatsoever.
- When you log out from your application, the 3rd party IdP usually do NOT log out synchronously. Imagine you are using Google sign-in for your app, a user logs out from your app, then finds out his/her Google account gets logged out too. Not a good practice IMHO.
- If you want your user to input login credentials at Logto every time they log in from your app, you can pass the `prompt=login` parameter to Logto. This guarantee you always see a login screen, instead of auto consenting.
- If you really want to log out from Logto synchronously when logging out from your app, you can send a POST request to Logto's "End session endpoint". E.g. `POST https://[tenant-id].logto.app/oidc/session/end?client_id=[your-app-id]`
